### PR TITLE
Introduce Github Actions workflows

### PR DESCRIPTION
**Pull request by blt**
This series of commits introduces two actions:

  * ci :: run build/test/etc on every push and pull request
  * security_audit :: nightly check security warnings against project deps

In addition, clippy suggestions have been folded in to the project and `cargo fmt`
run.

### CODE REVIEW

**Comment by jjl** [comment]
Hello! I've not used github actions before. does it all just happen? i may have gotten the wrong end of the stick but it looked like i needed to set up a builder somewhere when i last looked? or did you do that?

Please feel free to correct me :)

**Comment by jjl** [comment]
I'm not a terribly big fan of automated formatting btw. I'll let it slide because you've mixed it in with a bunch of other work, but automated formatting makes me sad in general.

**Comment by blt** [comment]
> Hello! I've not used github actions before. does it all just happen? i may have gotten the wrong end of the stick but it looked like i needed to set up a builder somewhere when i last looked? or did you do that?

This commit sets that up. Actions are available by default these days but you still need to have workflow configuration in place to enable it. Once this PR is merged they'll be flipped on in this repo. 

> I'm not a terribly big fan of automated formatting btw. I'll let it slide because you've mixed it in with a bunch of other work, but automated formatting makes me sad in general.

The commit could be backed out if you want. FWIW the workflow also enforces standard formatting style by running `cargo fmt`.

**Comment by jjl** [comment]
I'll relent on the one-off formatting, but could you please remove the automatic pushiness? Same goes with your other PR on supervisor, I guess.

**Comment by jjl** [comment]
Thanks!

**Pull request merged**
